service: product-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  env: dev
  stage: ${opt:stage, 'dev'}

  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  get-product-list:
    handler: handler.getProductList
    events:
      - http:
          path: products
          method: get
          cors: true

  get-product-by-id:
    handler: handler.getProductByID
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true

  post-product-to-list:
    handler: handler.postProductToList
    events:
      - http:
          path: products
          method: post
          cors: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceInclude:
        - pg
    packager: "npm"
    excludeFiles: product-service/**/*.test.js

  dotenv:
    path: ./.env.dev
    required:
      file: true
  serverless-offline:
    httpPort: 3000
