service: authorization-service
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  env: dev
  stage: ${opt:stage, 'dev'}

resources:
  Outputs:
    AuthorizationARN:
      Export:
        Name: basicAuthorizer
      Value:
        Fn::GetAtt: [BasicAuthorizerLambdaFunction, Arn]

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: false
    excludeFiles: authorization-service/**/*.test.js
  dotenv:
    path: ./.env.dev
    required:
      file: true
  serverless-offline:
    httpPort: 3000
